/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List webhook subscribers
         * @description Every registered receiver with its event filter. Signing secrets are never returned.
         */
        get: operations["list"];
        put?: never;
        /**
         * Register a webhook subscriber
         * @description Registers a receiver for snapshot lifecycle events. The signing secret is returned exactly once, in this response, and is never readable afterwards.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a held snapshot
         * @description Marks the snapshot rejected with the reviewer identity and timestamp; its content is never served.
         */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a held snapshot
         * @description Publishes the snapshot to the git facade and records the reviewer identity and timestamp. Only held snapshots can be approved.
         */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List marketplaces and their snapshots
         * @description All registered marketplaces with every snapshot and its state (held, approved, or rejected).
         */
        get: operations["listMarketplaces"];
        put?: never;
        /**
         * Register a marketplace
         * @description Registers an upstream git skill marketplace by clone URL. The URL scheme must be on the configured allowlist (default http/https). The ingested ref is set by the gateway (the upstream default branch) and cannot be overridden; a request supplying any other ref is rejected.
         */
        post: operations["registerMarketplace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplaces/{name}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest the upstream default branch
         * @description Fetches the marketplace's upstream default branch into quarantine and records an immutable snapshot pinned to the upstream commit SHA. The snapshot is held until a reviewer approves it; manifests declaring non-local plugin sources are rejected.
         */
        post: operations["ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDocs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/scalar.js": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScalarJs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recent delivery attempts
         * @description Most recent deliveries first, with state, attempt count, and the last response status or error — the operator's view of a failing integration.
         */
        get: operations["deliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshot provenance
         * @description What was served, from where, and who approved it: upstream URL, upstream commit SHA, state, reviewer, and timestamps.
         */
        get: operations["provenance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshot content inventory
         * @description The plugins declared by the snapshot's marketplace manifest and the skills found under each plugin's source tree — the basis for future per-plugin/per-skill limiting.
         */
        get: operations["snapshotContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Username of the authenticated browser session.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch audit ledger
         * @description Append-only record of every git facade fetch: client source address, authenticated identity, repository, ref, commit SHA, and timestamp. Portal actions are not in this ledger; approvals live in snapshot provenance.
         */
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a webhook subscriber
         * @description Removes the subscriber and its delivery history; no further events are queued for it.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Webhook subscriber registration request */
        CreateSubscriberRequest: {
            /**
             * @description Gateway-local subscriber name
             * @example ci-bot
             */
            name?: string;
            /**
             * @description Target URL; scheme must be on the configured allowlist (default http/https)
             * @example https://ci.example.com/hooks/skills-gateway
             */
            url?: string;
            /**
             * @description Comma-delimited event filter, or * for every event
             * @example snapshot.approved,snapshot.rejected
             */
            events?: string;
        };
        /** @description A freshly created subscriber; the only time the signing secret is ever returned */
        CreatedSubscriber: {
            /**
             * Format: int64
             * @description Subscriber id
             */
            id?: number;
            /** @description Subscriber name */
            name?: string;
            /** @description Target URL */
            url?: string;
            /** @description Comma-delimited event filter, or * for all */
            events?: string;
            /** @description Signing secret - shown exactly once */
            secret?: string;
            /**
             * Format: date-time
             * @description Creation time
             */
            createdAt?: string;
        };
        /** @description Token creation request */
        CreateTokenRequest: {
            /**
             * @description Human-readable token name
             * @example ci-runner
             */
            name?: string;
        };
        /** @description A freshly issued token; the only time the cleartext is ever returned */
        IssuedToken: {
            /**
             * Format: int64
             * @description Token id
             */
            id?: number;
            /** @description Token name */
            name?: string;
            /** @description Cleartext token value - shown exactly once, only a hash is stored */
            token?: string;
            /**
             * Format: date-time
             * @description Creation time
             */
            createdAt?: string;
        };
        /** @description An immutable, SHA-identified snapshot of an upstream marketplace */
        Snapshot: {
            /**
             * Format: int64
             * @description Snapshot id
             */
            id?: number;
            /**
             * Format: int64
             * @description Owning marketplace id
             */
            marketplaceId?: number;
            /** @description Upstream commit SHA the snapshot is pinned to */
            sha?: string;
            /**
             * @description held, approved, or rejected
             * @enum {string}
             */
            state?: "held" | "approved" | "rejected";
            /** @description Policy violation that rejected the snapshot, or null */
            violation?: string;
            /**
             * Format: date-time
             * @description Ingestion time
             */
            createdAt?: string;
            /** @description Reviewer who decided, or null while held */
            decidedBy?: string;
            /**
             * Format: date-time
             * @description Decision time, or null while held
             */
            decidedAt?: string;
        };
        /** @description Marketplace registration request */
        RegisterMarketplaceRequest: {
            /**
             * @description Gateway-local marketplace name; becomes the facade clone path /git/{name}
             * @example corp-marketplace
             */
            name?: string;
            /**
             * @description Upstream clone URL; scheme must be on the configured allowlist (default http/https)
             * @example https://github.com/acme/skills-marketplace.git
             */
            url?: string;
            /**
             * @description Must be omitted or equal the upstream default branch; the ingested ref is the gateway's decision, never the consumer's (GW_0017)
             * @example main
             */
            ref?: string;
        };
        /** @description A registered upstream marketplace */
        Marketplace: {
            /** Format: int64 */
            id?: number;
            name?: string;
            url?: string;
            /** Format: date-time */
            createdAt?: string;
            /** @description Detected forge (github, gitlab, bitbucket, azure-devops, gitea) or null */
            forge?: string;
            /** @description Project path on the forge */
            forgeProject?: string;
            /** @description Project description from the forge */
            description?: string;
            /**
             * Format: date-time
             * @description Last upstream update as reported by the forge
             */
            upstreamUpdatedAt?: string;
        };
        /** @description A webhook subscriber without its signing secret */
        SubscriberView: {
            /**
             * Format: int64
             * @description Subscriber id
             */
            id?: number;
            /** @description Subscriber name */
            name?: string;
            /** @description Target URL */
            url?: string;
            /** @description Comma-delimited event filter, or * */
            events?: string;
            /** @description Whether deliveries are queued for this subscriber */
            enabled?: boolean;
            /**
             * Format: date-time
             * @description Creation time
             */
            createdAt?: string;
        };
        /** @description One webhook delivery: an event queued for a subscriber, with its attempt history */
        WebhookDelivery: {
            /**
             * Format: int64
             * @description Delivery id; sent as the de-duplication header
             */
            id?: number;
            /**
             * Format: int64
             * @description Owning subscriber id
             */
            subscriberId?: number;
            /** @description Lifecycle event name */
            event?: string;
            /** @description Serialized JSON body; the exact bytes that are signed and sent */
            payload?: string;
            /**
             * @description pending, delivered, or failed
             * @enum {string}
             */
            state?: "pending" | "delivered" | "failed";
            /**
             * Format: int32
             * @description Attempts made so far
             */
            attempts?: number;
            /**
             * Format: date-time
             * @description When the next attempt becomes due
             */
            nextAttemptAt?: string;
            /**
             * Format: int32
             * @description HTTP status of the last attempt, or null
             */
            lastStatus?: number;
            /** @description Error of the last attempt, or null */
            lastError?: string;
            /**
             * Format: date-time
             * @description Enqueue time
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Last state change
             */
            updatedAt?: string;
        };
        /** @description A token without its secret; the cleartext is only returned at creation */
        TokenView: {
            /**
             * Format: int64
             * @description Token id
             */
            id?: number;
            /** @description Token name */
            name?: string;
            /**
             * Format: date-time
             * @description Creation time
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Revocation time, or null while active
             */
            revokedAt?: string;
        };
        /** @description Provenance of a snapshot: what was served, from where, and who approved it */
        Provenance: {
            /** Format: int64 */
            snapshotId?: number;
            marketplace?: string;
            upstreamUrl?: string;
            upstreamSha?: string;
            state?: string;
            violation?: string;
            /** Format: date-time */
            ingestedAt?: string;
            decidedBy?: string;
            /** Format: date-time */
            decidedAt?: string;
        };
        /** @description A plugin declared by the marketplace manifest */
        PluginContent: {
            /** @description Plugin name from the manifest */
            name?: string;
            /** @description Plugin description from the manifest */
            description?: string;
            /** @description Relative source path inside the marketplace repository */
            source?: string;
            /** @description Skills found under <source>/skills/ */
            skills?: components["schemas"]["SkillInfo"][];
        };
        /** @description A skill found under a plugin's source tree */
        SkillInfo: {
            /** @description Skill directory name */
            name?: string;
            /** @description Path of the SKILL.md within the snapshot */
            path?: string;
        };
        /** @description What a snapshot ships: the manifest's plugins and their skills */
        SnapshotContent: {
            /**
             * Format: int64
             * @description Snapshot id
             */
            snapshotId?: number;
            /** @description Upstream commit SHA */
            sha?: string;
            /** @description held, approved, or rejected */
            state?: string;
            /** @description Plugins declared by the manifest */
            plugins?: components["schemas"]["PluginContent"][];
        };
        /** @description A registered marketplace with its snapshots and forge metadata */
        MarketplaceView: {
            /**
             * Format: int64
             * @description Marketplace id
             */
            id?: number;
            /** @description Gateway-local name (also the facade clone path) */
            name?: string;
            /** @description Upstream clone URL */
            url?: string;
            /**
             * Format: date-time
             * @description Registration time
             */
            createdAt?: string;
            /** @description Detected forge (github, gitlab, bitbucket, azure-devops, gitea) or null */
            forge?: string;
            /** @description Project path on the forge, e.g. acme/skills */
            forgeProject?: string;
            /** @description Project description from the forge */
            description?: string;
            /**
             * Format: date-time
             * @description Last upstream update as reported by the forge
             */
            upstreamUpdatedAt?: string;
            /** @description All snapshots of this marketplace, any state */
            snapshots?: components["schemas"]["Snapshot"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubscriberView"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriberRequest"];
            };
        };
        responses: {
            /** @description Subscriber registered; response carries the show-once secret */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSubscriber"];
                };
            };
            /** @description Disallowed URL scheme, or an unknown event name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSubscriber"];
                };
            };
            /** @description A subscriber with that name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSubscriber"];
                };
            };
            /** @description Invalid subscriber name */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSubscriber"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenView"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssuedToken"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Snapshot is not in the held state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot approved and now served */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Snapshot is not in the held state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    listMarketplaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MarketplaceView"][];
                };
            };
        };
    };
    registerMarketplace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterMarketplaceRequest"];
            };
        };
        responses: {
            /** @description Marketplace registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Marketplace"];
                };
            };
            /** @description Disallowed URL scheme, or a ref other than the default branch */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Marketplace"];
                };
            };
            /** @description A marketplace with that name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Marketplace"];
                };
            };
            /** @description Invalid marketplace name */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Marketplace"];
                };
            };
        };
    };
    ingest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot recorded (held, or rejected on policy violation) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Marketplace not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Upstream fetch failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    getDocs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getScalarJs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    deliveries: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WebhookDelivery"][];
                };
            };
        };
    };
    provenance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provenance record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Provenance"];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Provenance"];
                };
            };
        };
    };
    snapshotContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugins and skills in the snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SnapshotContent"];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SnapshotContent"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    audit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscriber deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subscriber not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
