package dev.skillsgateway.server.config;

import io.github.reqstool.annotations.Requirements;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

/** SBOM exposure via the actuator sbom endpoint (management.endpoints.web.exposure). */
@Component
public class SbomEndpointConfig {

    private static final Logger log = LoggerFactory.getLogger(SbomEndpointConfig.class);
    private static final String SBOM_RESOURCE = "META-INF/sbom/application.cdx.json";

    @EventListener(ApplicationReadyEvent.class)
    @Requirements({"GW_0014"})
    public void verifySbomPresent() {
        if (!new ClassPathResource(SBOM_RESOURCE).exists()) {
            // Generated by the cyclonedx plugin at build time; IDE runs may lack it.
            log.warn("classpath resource {} is missing; /actuator/sbom will have no application SBOM", SBOM_RESOURCE);
        }
    }
}
