# yaml-language-server: $schema=https://raw.githubusercontent.com/reqstool/reqstool-client/main/src/reqstool/resources/schemas/v1/reqstool_config.schema.json

language: java
build: maven
resources:
  requirements: requirements.yml
  software_verification_cases: software_verification_cases.yml
  annotations: ../../target/reqstool/annotations.yml
  test_results:
    - ../../target/surefire-reports/**/*.xml
