/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit/sinks/{id}/cursor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set an audit export sink's ledger position
         * @description Replay: setting the position back re-delivers every ledger entry after it on the next export pass. Receivers de-duplicate on the ledger sequence carried by each entry.
         */
        put: operations["setCursor"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List webhook subscribers
         * @description Every registered receiver with its event filter. Signing secrets are never returned.
         */
        get: operations["list"];
        put?: never;
        /**
         * Register a webhook subscriber
         * @description Registers a receiver for snapshot lifecycle events. The signing secret is returned exactly once, in this response, and is never readable afterwards.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/waivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a vetting finding on this snapshot's marketplace
         * @description Records a scoped, expiring waiver for one finding rule. The marketplace — and, for SNAPSHOT scope, the commit SHA — are taken from the snapshot, so a waiver cannot be mis-scoped to content it does not belong to. A justification, the acting identity and a future expiry are all mandatory; an unlimited waiver cannot be expressed. While an active waiver covers a finding, that finding no longer contributes to the snapshot's effective vetting outcome.
         */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/revet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-vet an approved snapshot now
         * @description Runs the vetting chain again over the snapshot's pinned content and records a new run with trigger revet-manual. If the run's effective outcome — after the waivers active right now — objects to the content, the violation is written to the ledger and announced as snapshot.revet_violation. In enforce mode the snapshot is then revoked and its published refs are removed; in warn mode, the default, publication is untouched. A run that only blocks because a connector errored or has not answered is recorded as inconclusive and never revokes anything.
         */
        post: operations["revetSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a soft-deleted snapshot
         * @description Clears the deletion marks, provided compaction has not yet removed the snapshot.
         */
        post: operations["restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a held or revoked snapshot
         * @description Marks the snapshot rejected with the reviewer identity and timestamp; its content is never served again. This is the terminal answer to a re-vetting revocation the reviewer does not intend to waive.
         */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a held or revoked snapshot
         * @description Publishes the snapshot to the git facade and records the reviewer identity and timestamp. Takes no request body. Held snapshots and snapshots that re-vetting revoked can be approved; a revoked one is re-published only by this fresh decision, behind the same gate, which means the violation that revoked it must have been waived or fixed first. A snapshot whose effective vetting outcome is blocked — its chain run objects and at least one blocking finding is not covered by an active waiver, including a snapshot with no chain run at all — is refused, and the problem document names both the blocking connectors and the uncovered findings. Record a scoped, expiring waiver for each of those findings and approve again; every waiver that let the approval through is written to the ledger.
         */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retention/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a retention evaluation pass
         * @description Soft-deletes every snapshot the policies select. Equivalent to what the scheduled pass does when retention is enabled.
         */
        post: operations["evaluate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retention/compact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a compaction pass
         * @description Permanently removes every soft-deleted snapshot whose restore window has elapsed, together with its pinned commit in the quarantine repository.
         */
        post: operations["compact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List marketplaces and their snapshots
         * @description All registered marketplaces with every snapshot and its state (held, approved, rejected, or revoked).
         */
        get: operations["listMarketplaces"];
        put?: never;
        /**
         * Register a marketplace
         * @description Registers an upstream git skill marketplace by clone URL. The URL scheme must be on the configured allowlist (default http/https). The ingested ref is set by the gateway (the upstream default branch) and cannot be overridden; a request supplying any other ref is rejected.
         */
        post: operations["registerMarketplace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplaces/{name}/revet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-vet every approved snapshot of a marketplace now
         * @description Runs the vetting chain again over every live approved snapshot of the marketplace, one run each, and applies the configured re-vetting mode to each result. This is the operational answer to a connector rule set or advisory feed that has just been updated.
         */
        post: operations["revetMarketplace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplaces/{name}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest the upstream default branch
         * @description Fetches the marketplace's upstream default branch into quarantine and records an immutable snapshot pinned to the upstream commit SHA. The snapshot is held until a reviewer approves it; manifests declaring non-local plugin sources are rejected.
         */
        post: operations["ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/sinks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List audit export sinks
         * @description Every registered sink with its target, its position in the ledger, and how many entries it still has to receive. Signing secrets are never returned.
         */
        get: operations["listSinks"];
        put?: never;
        /**
         * Register an audit export sink
         * @description Registers a push consumer of the ledger. Batches are POSTed to the target URL by the same signed, retried delivery machinery as lifecycle webhooks; the signing secret is returned exactly once, in this response.
         */
        post: operations["createSink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDocs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs/scalar.js": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScalarJs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recent delivery attempts
         * @description Most recent deliveries first, with state, attempt count, and the last response status or error — the operator's view of a failing integration.
         */
        get: operations["deliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/vetting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshot vetting verdicts
         * @description The snapshot's latest vetting chain run: each connector's verdict in chain order, the findings behind it, the waivers currently suppressing any of them, and the fail-closed effective aggregate that gates approval. A snapshot the chain has never run against reports a blocked outcome and no run.
         */
        get: operations["vetting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshot provenance
         * @description What was served, from where, and who approved it: upstream URL, upstream commit SHA, state, reviewer, and timestamps.
         */
        get: operations["provenance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/fetchers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who fetched this snapshot
         * @description Every authenticated identity that received this snapshot's content through the git facade, with how many times and when it last did — the blast radius of a retroactive violation, answered from the append-only fetch ledger. Only pack transfers count: a ref advertisement means the client asked, not that it received anything.
         */
        get: operations["fetchers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshot content inventory
         * @description The plugins declared by the snapshot's marketplace manifest and the skills found under each plugin's source tree — the basis for future per-plugin/per-skill limiting.
         */
        get: operations["snapshotContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retention/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview the retention candidates
         * @description The snapshots the policies in force would delete right now, each with the criterion that selected it. A dry run: nothing is written.
         */
        get: operations["candidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Username of the authenticated browser session.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketplaces/{name}/waivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A marketplace's vetting waivers
         * @description Every waiver recorded for the marketplace, newest first, active and lapsed alike. A lapsed or revoked waiver is kept and returned with active=false: the record of what was once accepted, by whom and until when is part of the audit trail.
         */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch audit ledger
         * @description Append-only record of every git facade fetch: client source address, authenticated identity, repository, ref, commit SHA, and timestamp. Portal actions are not in this ledger; approvals live in snapshot provenance.
         */
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream the audit ledger as NDJSON
         * @description Newline-delimited JSON, one ledger entry per line in ascending ledger sequence, for ingestion by an external SIEM. Poll incrementally by passing the sequence from the X-Skills-Gateway-Audit-Cursor response header back as 'after'; an empty body means the consumer is caught up. Entries younger than the commit-settling lag are withheld so a cursor can never step over an in-flight append.
         */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a webhook subscriber
         * @description Removes the subscriber and its delivery history; no further events are queued for it.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waivers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Withdraw a waiver
         * @description Revokes the waiver. It stops suppressing its finding immediately — the effective vetting outcome is recomputed on every read — so a snapshot that was cleared only by this waiver becomes blocked again. The row is kept, with its revoker and time.
         */
        delete: operations["revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Soft-delete a snapshot
         * @description Marks the snapshot deleted and restorable until the end of the marketplace's restore window; its vetting state is unchanged. Approved snapshots are served by the git facade and can never be deleted.
         */
        delete: operations["softDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/sinks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an audit export sink
         * @description Removes the sink and its delivery channel; no further batches are queued for it.
         */
        delete: operations["deleteSink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Cursor reset request */
        CursorRequest: {
            /**
             * Format: int64
             * @description Ledger sequence to resume after; entries following it are delivered again
             */
            after?: number;
        };
        /** @description A registered audit export sink */
        SinkView: {
            /**
             * Format: int64
             * @description Sink id
             */
            id?: number;
            /** @description Sink name */
            name?: string;
            /** @description Sink kind */
            kind?: string;
            /** @description Target URL */
            url?: string;
            /**
             * Format: int64
             * @description Ledger sequence last handed to this sink
             */
            cursorPosition?: number;
            /**
             * Format: int64
             * @description Highest ledger sequence written so far
             */
            ledgerHead?: number;
            /**
             * Format: int64
             * @description Ledger entries not yet handed to this sink
             */
            behind?: number;
            /**
             * Format: int32
             * @description Maximum ledger entries per batch
             */
            batchSize?: number;
            /** @description Whether export passes run for this sink */
            enabled?: boolean;
            /**
             * Format: date-time
             * @description Creation time
             */
            createdAt?: string;
        };
        /** @description Webhook subscriber registration request */
        CreateSubscriberRequest: {
            /**
             * @description Gateway-local subscriber name
             * @example ci-bot
             */
            name?: string;
            /**
             * @description Target URL; scheme must be on the configured allowlist (default http/https)
             * @example https://ci.example.com/hooks/skills-gateway
             */
            url?: string;
            /**
             * @description Comma-delimited event filter, or * for every event
             * @example snapshot.approved,snapshot.rejected
             */
            events?: string;
        };
        /** @description A freshly created subscriber; the only time the signing secret is ever returned */
        CreatedSubscriber: {
            /**
             * Format: int64
             * @description Subscriber id
             */
            id?: number;
            /** @description Subscriber name */
            name?: string;
            /** @description Target URL */
            url?: string;
            /** @description Comma-delimited event filter, or * for all */
            events?: string;
            /** @description Signing secret - shown exactly once */
            secret?: string;
            /**
             * Format: date-time
             * @description Creation time
             */
            createdAt?: string;
        };
        /** @description Token creation request */
        CreateTokenRequest: {
            /**
             * @description Human-readable token name
             * @example ci-runner
             */
            name?: string;
        };
        /** @description A freshly issued token; the only time the cleartext is ever returned */
        IssuedToken: {
            /**
             * Format: int64
             * @description Token id
             */
            id?: number;
            /** @description Token name */
            name?: string;
            /** @description Cleartext token value - shown exactly once, only a hash is stored */
            token?: string;
            /**
             * Format: date-time
             * @description Creation time
             */
            createdAt?: string;
        };
        /** @description Request to accept one finding rule on a snapshot's marketplace, until an expiry */
        WaiverRequest: {
            /**
             * @description Finding rule identifier to accept
             * @example aws-access-key-id
             */
            ruleId: string;
            /**
             * @description SNAPSHOT pins the waiver to this snapshot's commit SHA; PATH applies it to a path in the marketplace and survives re-ingestion
             * @enum {string}
             */
            scope: "SNAPSHOT" | "PATH";
            /**
             * @description Repository-relative path for PATH scope; ignored for SNAPSHOT scope, which always takes the snapshot's own SHA
             * @example plugins/hello
             */
            path?: string;
            /** @description Why this risk is accepted; recorded and shown to the next reviewer */
            justification: string;
            /**
             * Format: date-time
             * @description When the acceptance lapses. Required and must be in the future: there are no unlimited waivers.
             * @example 2026-12-31T00:00:00Z
             */
            expiresAt: string;
        };
        /** @description A waiver as returned by the API, with its activity resolved as of now */
        WaiverView: {
            /**
             * Format: int64
             * @description Waiver id
             */
            id?: number;
            /** @description Marketplace the waiver belongs to */
            marketplace?: string;
            /**
             * @description Finding rule identifier being accepted
             * @example aws-access-key-id
             */
            ruleId?: string;
            /**
             * @description How the scope value is matched
             * @enum {string}
             */
            scope?: "SNAPSHOT" | "PATH";
            /** @description A commit SHA for snapshot scope, a repository-relative path for path scope */
            scopeValue?: string;
            /** @description Why the risk is accepted */
            justification?: string;
            /** @description Identity that accepted the risk */
            approvedBy?: string;
            /**
             * Format: date-time
             * @description When the waiver was created
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description When the acceptance lapses; never null
             */
            expiresAt?: string;
            /**
             * Format: date-time
             * @description When the waiver was revoked, or null
             */
            revokedAt?: string;
            /** @description Identity that revoked it, or null */
            revokedBy?: string;
            /** @description Whether the waiver suppresses anything right now */
            active?: boolean;
        };
        /** @description An identity that fetched a snapshot's content through the git facade */
        Fetcher: {
            /** @description Authenticated identity that fetched it */
            principal?: string;
            /**
             * Format: int64
             * @description How many times it received a pack for this commit
             */
            fetches?: number;
            /**
             * Format: date-time
             * @description The most recent of those fetches
             */
            lastFetch?: string;
        };
        /** @description What one re-vetting run concluded about one approved snapshot */
        RevetResult: {
            /**
             * Format: int64
             * @description Snapshot that was re-vetted
             */
            snapshotId?: number;
            /** @description Marketplace it belongs to */
            marketplace?: string;
            /** @description Commit SHA that was re-vetted */
            sha?: string;
            /**
             * Format: int64
             * @description Chain run this re-vetting recorded
             */
            runId?: number;
            /**
             * @description What the run means for already-approved content
             * @enum {string}
             */
            classification?: "CLEAR" | "VIOLATION" | "INCONCLUSIVE";
            /**
             * @description The effective vetting outcome after active waivers
             * @enum {string}
             */
            outcome?: "CLEAR" | "CLEAR_WITH_WAIVERS" | "BLOCKED";
            /** @description Whether the snapshot was revoked and unpublished as a result */
            revoked?: boolean;
            /**
             * @description Mode in force for this run: WARN records the violation and leaves publication alone, ENFORCE revokes
             * @enum {string}
             */
            mode?: "WARN" | "ENFORCE";
            /** @description Blocking findings no active waiver covers; the reason for a violation */
            uncovered?: components["schemas"]["UncoveredFinding"][];
            /** @description Identities that fetched this commit through the facade before the violation */
            affected?: components["schemas"]["Fetcher"][];
        };
        /** @description A blocking finding that no active waiver covers */
        UncoveredFinding: {
            /** @description Connector whose verdict carried the finding */
            connector?: string;
            /** @description Finding rule identifier */
            ruleId?: string;
            /** @description Where the finding was located */
            location?: string;
            /**
             * @description How much it matters
             * @enum {string}
             */
            severity?: "INFO" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** @description Reviewer-facing explanation */
            message?: string;
        };
        /** @description An immutable, SHA-identified snapshot of an upstream marketplace */
        Snapshot: {
            /**
             * Format: int64
             * @description Snapshot id
             */
            id?: number;
            /**
             * Format: int64
             * @description Owning marketplace id
             */
            marketplaceId?: number;
            /** @description Upstream commit SHA the snapshot is pinned to */
            sha?: string;
            /**
             * @description held, approved, rejected, or revoked (retroactively quarantined by re-vetting)
             * @enum {string}
             */
            state?: "held" | "approved" | "rejected" | "revoked";
            /** @description Policy or vetting violation that rejected or revoked the snapshot, or null */
            violation?: string;
            /**
             * Format: date-time
             * @description Ingestion time
             */
            createdAt?: string;
            /** @description Reviewer who decided, or null while held */
            decidedBy?: string;
            /**
             * Format: date-time
             * @description Decision time, or null while held
             */
            decidedAt?: string;
            /**
             * Format: date-time
             * @description When re-vetting revoked the snapshot, or null
             */
            revokedAt?: string;
            /** @description Identity that revoked it, or null */
            revokedBy?: string;
            /**
             * Format: date-time
             * @description When the snapshot was soft-deleted, or null when it is live
             */
            deletedAt?: string;
            /** @description Retention criterion or administrative reason for the deletion */
            deletedReason?: string;
            /**
             * Format: date-time
             * @description End of the restore window; after it compaction removes the snapshot permanently
             */
            purgeAfter?: string;
        };
        /** @description Outcome of a retention pass */
        PassResult: {
            /**
             * Format: int32
             * @description Snapshots evaluated as eligible
             */
            selected?: number;
            /**
             * Format: int32
             * @description Snapshots acted on by this pass
             */
            acted?: number;
        };
        /** @description Marketplace registration request */
        RegisterMarketplaceRequest: {
            /**
             * @description Gateway-local marketplace name; becomes the facade clone path /git/{name}
             * @example corp-marketplace
             */
            name?: string;
            /**
             * @description Upstream clone URL; scheme must be on the configured allowlist (default http/https)
             * @example https://github.com/acme/skills-marketplace.git
             */
            url?: string;
            /**
             * @description Must be omitted or equal the upstream default branch; the ingested ref is the gateway's decision, never the consumer's (GW_0017)
             * @example main
             */
            ref?: string;
        };
        /** @description A registered upstream marketplace */
        Marketplace: {
            /** Format: int64 */
            id?: number;
            name?: string;
            url?: string;
            /** Format: date-time */
            createdAt?: string;
            /** @description Detected forge (github, gitlab, bitbucket, azure-devops, gitea) or null */
            forge?: string;
            /** @description Project path on the forge */
            forgeProject?: string;
            /** @description Project description from the forge */
            description?: string;
            /**
             * Format: date-time
             * @description Last upstream update as reported by the forge
             */
            upstreamUpdatedAt?: string;
        };
        /** @description Audit export sink registration request */
        CreateSinkRequest: {
            /**
             * @description Gateway-local sink name
             * @example siem
             */
            name?: string;
            /**
             * @description Target URL batches are POSTed to; scheme must be on the configured allowlist (default http/https)
             * @example https://siem.example.com/ingest/skills-gateway
             */
            url?: string;
            /**
             * Format: int64
             * @description Ledger sequence to start after; omit to start at the beginning
             * @example 0
             */
            after?: number;
            /**
             * Format: int32
             * @description Maximum ledger entries per batch
             * @example 500
             */
            batchSize?: number;
        };
        /** @description A newly registered audit export sink, with its show-once signing secret */
        CreatedSink: {
            /**
             * Format: int64
             * @description Sink id
             */
            id?: number;
            /** @description Sink name */
            name?: string;
            /** @description Sink kind */
            kind?: string;
            /** @description Target URL batches are POSTed to */
            url?: string;
            /**
             * Format: int64
             * @description Ledger sequence the sink starts after
             */
            cursorPosition?: number;
            /**
             * Format: int32
             * @description Maximum ledger entries per batch
             */
            batchSize?: number;
            /** @description Signing secret of the sink's delivery channel - shown exactly once */
            secret?: string;
            /**
             * Format: date-time
             * @description Creation time
             */
            createdAt?: string;
        };
        /** @description A webhook subscriber without its signing secret */
        SubscriberView: {
            /**
             * Format: int64
             * @description Subscriber id
             */
            id?: number;
            /** @description Subscriber name */
            name?: string;
            /** @description Target URL */
            url?: string;
            /** @description Comma-delimited event filter, or * */
            events?: string;
            /** @description Whether deliveries are queued for this subscriber */
            enabled?: boolean;
            /**
             * Format: date-time
             * @description Creation time
             */
            createdAt?: string;
        };
        /** @description One webhook delivery: an event queued for a subscriber, with its attempt history */
        WebhookDelivery: {
            /**
             * Format: int64
             * @description Delivery id; sent as the de-duplication header
             */
            id?: number;
            /**
             * Format: int64
             * @description Owning subscriber id
             */
            subscriberId?: number;
            /** @description Lifecycle event name */
            event?: string;
            /** @description Serialized JSON body; the exact bytes that are signed and sent */
            payload?: string;
            /**
             * @description pending, delivered, or failed
             * @enum {string}
             */
            state?: "pending" | "delivered" | "failed";
            /**
             * Format: int32
             * @description Attempts made so far
             */
            attempts?: number;
            /**
             * Format: date-time
             * @description When the next attempt becomes due
             */
            nextAttemptAt?: string;
            /**
             * Format: int32
             * @description HTTP status of the last attempt, or null
             */
            lastStatus?: number;
            /** @description Error of the last attempt, or null */
            lastError?: string;
            /**
             * Format: date-time
             * @description Enqueue time
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Last state change
             */
            updatedAt?: string;
        };
        /** @description A token without its secret; the cleartext is only returned at creation */
        TokenView: {
            /**
             * Format: int64
             * @description Token id
             */
            id?: number;
            /** @description Token name */
            name?: string;
            /**
             * Format: date-time
             * @description Creation time
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description Revocation time, or null while active
             */
            revokedAt?: string;
        };
        /** @description A connector configured in the vetting chain */
        ConnectorView: {
            /** @description Stable connector name */
            name?: string;
            /**
             * Format: int32
             * @description Position in the chain
             */
            order?: number;
            /** @description What the connector looks for, and what it cannot see */
            description?: string;
        };
        /** @description One thing a vetting connector found in a snapshot */
        Finding: {
            /**
             * @description Stable rule identifier, e.g. aws-access-key-id
             * @example aws-access-key-id
             */
            id?: string;
            /**
             * @description How much the finding matters
             * @enum {string}
             */
            severity?: "INFO" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** @description Where in the snapshot it was found, normally path:line */
            location?: string;
            /** @description Reviewer-facing explanation; never echoes the matched secret */
            message?: string;
        };
        /** @description One execution of the vetting chain against a snapshot */
        Run: {
            /**
             * Format: int64
             * @description Chain run id
             */
            runId?: number;
            /**
             * Format: int64
             * @description Snapshot the run vetted
             */
            snapshotId?: number;
            /**
             * @description What caused the run
             * @enum {string}
             */
            trigger?: "ingestion" | "revet-scheduled" | "revet-manual";
            /**
             * @description Fail-closed aggregate of the run's verdicts
             * @enum {string}
             */
            outcome?: "CLEAR" | "CLEAR_WITH_WAIVERS" | "BLOCKED";
            /**
             * Format: date-time
             * @description When the run started
             */
            startedAt?: string;
            /**
             * Format: date-time
             * @description When the run finished, or null if it never did
             */
            finishedAt?: string;
            /**
             * @description Identity of the chain that produced the run: connector@version in chain order
             * @example prompt-injection@1,secret-scan@1
             */
            chain?: string;
            /** @description The run's verdicts, in chain order */
            verdicts?: components["schemas"]["VerdictView"][];
        };
        /** @description A finding an active waiver is currently suppressing */
        Suppression: {
            /** @description Connector whose verdict carried the finding */
            connector?: string;
            /** @description Finding rule identifier */
            ruleId?: string;
            /** @description Where the finding was located */
            location?: string;
            /**
             * Format: int64
             * @description Waiver suppressing it
             */
            waiverId?: number;
            /** @description Identity that accepted the risk */
            approvedBy?: string;
            /**
             * Format: date-time
             * @description When the acceptance lapses
             */
            expiresAt?: string;
        };
        /** @description One connector's recorded verdict within a chain run */
        VerdictView: {
            /**
             * Format: int64
             * @description Verdict id
             */
            verdictId?: number;
            /** @description Connector name */
            connector?: string;
            /**
             * Format: int32
             * @description Position of the connector in the chain
             */
            position?: number;
            /**
             * @description The connector's conclusion
             * @enum {string}
             */
            state?: "PASS" | "WARN" | "FAIL" | "ERROR" | "PENDING";
            /** @description One-line summary of the findings, or null when there are none */
            detail?: string;
            /** @description External report URL, when the connector produced one */
            reportUrl?: string;
            /** @description What the connector found */
            findings?: components["schemas"]["Finding"][];
        };
        /** @description A snapshot's latest vetting chain run, the waivers over it, and the chain that produced it */
        VettingView: {
            /**
             * Format: int64
             * @description Snapshot id
             */
            snapshotId?: number;
            /**
             * @description The effective outcome, which is what gates approval: the run's verdicts with every waived finding removed. CLEAR_WITH_WAIVERS means nothing objects any more only because an active waiver is suppressing a finding. A snapshot with no run is blocked.
             * @enum {string}
             */
            outcome?: "CLEAR" | "CLEAR_WITH_WAIVERS" | "BLOCKED";
            /**
             * @description What the connectors themselves concluded, before any waiver was applied
             * @enum {string}
             */
            recordedOutcome?: "CLEAR" | "BLOCKED";
            /** @description The latest run with its verdicts and findings, or null if the chain never ran */
            run?: components["schemas"]["Run"];
            /** @description Findings an active waiver is currently suppressing, keyed by connector, rule and location */
            suppressed?: components["schemas"]["Suppression"][];
            /** @description Blocking findings that no active waiver covers; the waivers approval still needs */
            uncovered?: components["schemas"]["UncoveredFinding"][];
            /** @description Waivers of this snapshot's marketplace whose rule appears in this run, active and lapsed alike, so an expired acceptance stays visible */
            waivers?: components["schemas"]["WaiverView"][];
            /** @description The connectors configured in the chain, in the order they run */
            connectors?: components["schemas"]["ConnectorView"][];
        };
        /** @description Provenance of a snapshot: what was served, from where, and who approved it */
        Provenance: {
            /** Format: int64 */
            snapshotId?: number;
            marketplace?: string;
            upstreamUrl?: string;
            upstreamSha?: string;
            state?: string;
            violation?: string;
            /** Format: date-time */
            ingestedAt?: string;
            decidedBy?: string;
            /** Format: date-time */
            decidedAt?: string;
            /**
             * Format: date-time
             * @description When re-vetting revoked the snapshot, or null
             */
            revokedAt?: string;
            /** @description Identity that revoked it, or null */
            revokedBy?: string;
        };
        /** @description A plugin declared by the marketplace manifest */
        PluginContent: {
            /** @description Plugin name from the manifest */
            name?: string;
            /** @description Plugin description from the manifest */
            description?: string;
            /** @description Relative source path inside the marketplace repository */
            source?: string;
            /** @description Skills found under <source>/skills/ */
            skills?: components["schemas"]["SkillInfo"][];
        };
        /** @description A skill found under a plugin's source tree */
        SkillInfo: {
            /** @description Skill directory name */
            name?: string;
            /** @description Path of the SKILL.md within the snapshot */
            path?: string;
        };
        /** @description What a snapshot ships: the manifest's plugins and their skills */
        SnapshotContent: {
            /**
             * Format: int64
             * @description Snapshot id
             */
            snapshotId?: number;
            /** @description Upstream commit SHA */
            sha?: string;
            /** @description held, approved, or rejected */
            state?: string;
            /** @description Plugins declared by the manifest */
            plugins?: components["schemas"]["PluginContent"][];
        };
        /** @description A snapshot a retention policy would delete, and the criterion that selected it */
        Candidate: {
            /**
             * Format: int64
             * @description Snapshot id
             */
            snapshotId?: number;
            /** @description Marketplace the snapshot belongs to */
            marketplace?: string;
            /** @description Upstream commit SHA the snapshot is pinned to */
            sha?: string;
            /** @description Vetting state; never approved, which is categorically ineligible */
            state?: string;
            /**
             * @description Criterion that selected the snapshot
             * @enum {string}
             */
            reason?: "held-too-long" | "superseded";
            /**
             * Format: date-time
             * @description Ingestion time
             */
            createdAt?: string;
        };
        /** @description A registered marketplace with its snapshots and forge metadata */
        MarketplaceView: {
            /**
             * Format: int64
             * @description Marketplace id
             */
            id?: number;
            /** @description Gateway-local name (also the facade clone path) */
            name?: string;
            /** @description Upstream clone URL */
            url?: string;
            /**
             * Format: date-time
             * @description Registration time
             */
            createdAt?: string;
            /** @description Detected forge (github, gitlab, bitbucket, azure-devops, gitea) or null */
            forge?: string;
            /** @description Project path on the forge, e.g. acme/skills */
            forgeProject?: string;
            /** @description Project description from the forge */
            description?: string;
            /**
             * Format: date-time
             * @description Last upstream update as reported by the forge
             */
            upstreamUpdatedAt?: string;
            /** @description All snapshots of this marketplace, any state */
            snapshots?: components["schemas"]["Snapshot"][];
        };
        StreamingResponseBody: unknown;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setCursor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CursorRequest"];
            };
        };
        responses: {
            /** @description Position updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SinkView"];
                };
            };
            /** @description Sink not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SinkView"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubscriberView"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriberRequest"];
            };
        };
        responses: {
            /** @description Subscriber registered; response carries the show-once secret */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSubscriber"];
                };
            };
            /** @description Disallowed URL scheme, or an unknown event name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSubscriber"];
                };
            };
            /** @description A subscriber with that name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSubscriber"];
                };
            };
            /** @description Invalid subscriber name */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSubscriber"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenView"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IssuedToken"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaiverRequest"];
            };
        };
        responses: {
            /** @description Waiver recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WaiverView"];
                };
            };
            /** @description Missing justification or expiry, an expiry in the past, or an unusable scope */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WaiverView"];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WaiverView"];
                };
            };
        };
    };
    revetSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The re-vetting run and what it concluded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevetResult"];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevetResult"];
                };
            };
            /** @description The snapshot is not approved; only served content is re-vetted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevetResult"];
                };
            };
        };
    };
    restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Snapshot is not deleted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Snapshot is neither held nor revoked */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot approved and now served */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Snapshot is neither held nor revoked, or its effective vetting outcome is blocked */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    evaluate: {
        parameters: {
            query?: {
                /** @description Restrict to one marketplace */
                marketplace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pass outcome */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PassResult"];
                };
            };
        };
    };
    compact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pass outcome */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PassResult"];
                };
            };
        };
    };
    listMarketplaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MarketplaceView"][];
                };
            };
        };
    };
    registerMarketplace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterMarketplaceRequest"];
            };
        };
        responses: {
            /** @description Marketplace registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Marketplace"];
                };
            };
            /** @description Disallowed URL scheme, or a ref other than the default branch */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Marketplace"];
                };
            };
            /** @description A marketplace with that name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Marketplace"];
                };
            };
            /** @description Invalid marketplace name */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Marketplace"];
                };
            };
        };
    };
    revetMarketplace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What the pass re-vetted and concluded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PassResult"];
                };
            };
            /** @description Marketplace not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PassResult"];
                };
            };
        };
    };
    ingest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot recorded (held, or rejected on policy violation) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Marketplace not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Upstream fetch failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    listSinks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SinkView"][];
                };
            };
        };
    };
    createSink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSinkRequest"];
            };
        };
        responses: {
            /** @description Sink registered; response carries the show-once secret */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSink"];
                };
            };
            /** @description Disallowed URL scheme */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSink"];
                };
            };
            /** @description A sink or webhook subscriber with that name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSink"];
                };
            };
            /** @description Invalid sink name */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSink"];
                };
            };
        };
    };
    getDocs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getScalarJs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    deliveries: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WebhookDelivery"][];
                };
            };
        };
    };
    vetting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The latest chain run and the configured chain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VettingView"];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VettingView"];
                };
            };
        };
    };
    provenance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provenance record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Provenance"];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Provenance"];
                };
            };
        };
    };
    fetchers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The identities that fetched the snapshot's content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fetcher"][];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Fetcher"][];
                };
            };
        };
    };
    snapshotContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugins and skills in the snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SnapshotContent"];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SnapshotContent"];
                };
            };
        };
    };
    candidates: {
        parameters: {
            query?: {
                /** @description Restrict to one marketplace */
                marketplace?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Candidate snapshots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Candidate"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The marketplace's waivers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WaiverView"][];
                };
            };
            /** @description Marketplace not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WaiverView"][];
                };
            };
        };
    };
    audit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entries after the cursor, newline-delimited */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["StreamingResponseBody"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscriber deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subscriber not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Waiver revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WaiverView"];
                };
            };
            /** @description Waiver not found, or already revoked */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WaiverView"];
                };
            };
        };
    };
    revoke_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    softDelete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot marked deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Snapshot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
            /** @description Snapshot is approved, or already deleted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    deleteSink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sink deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sink not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
